// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCZIHSQd4-vGkQ58MSRAm0Jt_ysS3TCgw',
    appId: '1:293905643672:web:e7ad9a39e34d71d70078ed',
    messagingSenderId: '293905643672',
    projectId: 'covid-detection-9c949',
    authDomain: 'covid-detection-9c949.firebaseapp.com',
    databaseURL: 'https://covid-detection-9c949-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'covid-detection-9c949.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW2nmMYWuFm_yubeXaRI7KyM1hpPhN9UI',
    appId: '1:293905643672:android:3a604b31bbacedd30078ed',
    messagingSenderId: '293905643672',
    projectId: 'covid-detection-9c949',
    databaseURL: 'https://covid-detection-9c949-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'covid-detection-9c949.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi_72qgrQBTGVEz5ZbJ2aWMWbPvXXyStI',
    appId: '1:293905643672:ios:3ae5359aac46f8560078ed',
    messagingSenderId: '293905643672',
    projectId: 'covid-detection-9c949',
    databaseURL: 'https://covid-detection-9c949-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'covid-detection-9c949.appspot.com',
    androidClientId: '293905643672-s2feqtsae43lbd97vn9q1g7n0k94iapc.apps.googleusercontent.com',
    iosClientId: '293905643672-ovk1i6noe0oqqpv5or2n63a7b6mp5ggh.apps.googleusercontent.com',
    iosBundleId: 'com.example.covidDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi_72qgrQBTGVEz5ZbJ2aWMWbPvXXyStI',
    appId: '1:293905643672:ios:3ae5359aac46f8560078ed',
    messagingSenderId: '293905643672',
    projectId: 'covid-detection-9c949',
    databaseURL: 'https://covid-detection-9c949-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'covid-detection-9c949.appspot.com',
    androidClientId: '293905643672-s2feqtsae43lbd97vn9q1g7n0k94iapc.apps.googleusercontent.com',
    iosClientId: '293905643672-ovk1i6noe0oqqpv5or2n63a7b6mp5ggh.apps.googleusercontent.com',
    iosBundleId: 'com.example.covidDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCZIHSQd4-vGkQ58MSRAm0Jt_ysS3TCgw',
    appId: '1:293905643672:web:e7ad9a39e34d71d70078ed',
    messagingSenderId: '293905643672',
    projectId: 'covid-detection-9c949',
    authDomain: 'covid-detection-9c949.firebaseapp.com',
    databaseURL: 'https://covid-detection-9c949-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'covid-detection-9c949.appspot.com',
  );

}